### ISSUE TITLE
Проблемы отображения на iPad после редизайна сайта ru.bem.info

### ISSUE THREAD

**Issue by Baskins** [bem-site/bem.info#102]
Вместе с классным редизайном ru.bem.info  прилетел баг
Раздел форум https://ru.bem.info/forum/
Теперь на айпаде (обычный 10 дюймов с ретиной) верстка шапки поехала и контент уехал вниз. Я сразу и не понял увидев пустой экран, но прокрутив вниз все стало понятно.
Ниже скриншоты, помогут понять суть бага
Проверялось в хроме и сафари
**В браузере Хром**
![Версия хрома](http://100creditov.ru/i/ru_bem_infoipad/IMG_0026.PNG)

![Хром](http://100creditov.ru/i/ru_bem_infoipad/IMG_0024.PNG)

![Хром](http://100creditov.ru/i/ru_bem_infoipad/IMG_0025.PNG)

**В браузере Сафари**
![Сафари](http://100creditov.ru/i/ru_bem_infoipad/IMG_0027.PNG)

![Сафари](http://100creditov.ru/i/ru_bem_infoipad/IMG_0028.PNG)

**Comment by vithar** [comment]
Не воспроизводится.
