### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by tadatuta** [bem-site/bem.info#121]
1. Search button moves on scroll
2. Use `nobr` for `i-bem` in `Справочное руководство по i-bem.js` in `sitemap` block
3. I'd switch `.search__form .input__control` to `color: #fff`
4. Tags on pages with long titles appear on top of the title and with strange left padding

**Comment by vithar** [comment]
> Use nobr for i-bem in Справочное руководство по i-bem.js in sitemap block

I can use html in md, it escaped by someone somewhere :(

**Comment by vithar** [comment]
> I'd switch .search__form .input__control to color: #fff

Done.

**Comment by vithar** [comment]
> Search button moves on scroll

File separate bug to @AnyaTyu

**Comment by vithar** [comment]
> Tags on pages with long titles appear on top of the title and with strange left padding

I'll refactor this piece of code in nearest future.
