### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by miripiruni** [bem-site/bem.info#127]
1. Arrows on the side entirely invisible.
2. Once the user has finished reading, he buries in the bottom of the page. Nothing suggests that there are the following section.

<img width="623" alt="screen shot 2016-06-22 at 12 32 26" src="https://cloud.githubusercontent.com/assets/144537/16261748/6693d46e-3875-11e6-9092-1c8107e5098b.png">

I propose to make a link with navigation noticeable. And be sure to add a link to the next section at the end.

**Comment by vithar** [comment]
Done in #185. Already in production.
