### ISSUE TITLE
Add version selector to documetation

### ISSUE THREAD

**Issue by miripiruni** [bem-site/bem.info#128]
Any package have it’s version. bem-xjst, i-bem, bem-core, etc. I propose to make version selector. At least for major releases.

**Comment by vithar** [comment]
Done.

**Comment by miripiruni** [comment]
I didnt saw version selector or any version marker on page.

**Comment by vithar** [comment]
@miripiruni You can see it in breadcrumbs in header.

**Comment by miripiruni** [comment]
@vithar in mobile version it’s invisible.

**Comment by vithar** [comment]
In mobile version it in hamburger menu.
