### ISSUE TITLE
Поиск для быстрой навигации.

### ISSUE THREAD

**Issue by belozyorcev** [bem-site/bem.info#132]
Всем привет. 

Заметил, что не совсем понятно куда лезть, когда заходишь на bem-info. Знаешь что нужно, но не знаешь где.

Хорошо бы, чтобы при сборке статей они мапились в какой-то файл (типо sitemap). 
И тогда можно было бы введя в поле поиска нужный инструмент быстро перейти на нужную страницу.

**Comment by vithar** [comment]
Нажми на лупу в правом верхнем углу.

**Comment by belozyorcev** [comment]
@vithar я сейчас красный как помидор )))
