### ISSUE TITLE
Предложение варианта выбора языка на сайте

### ISSUE THREAD

**Issue by palegrow** [bem-site/bem.info#149]
В телеграмном чате видел дискуссию как удобней сделать переключение между языками на сайте. Одним из доводов, что выпадающий список это плохо, был пример, что читатель может не понять, на каком он сейчас языке. Может, этого можно избежать, если на кнопке выпадающего списка рядом с текущим языком поставить значок глобуса (https://material.io/icons/#ic_language). Такой значок стоит на стоковых клавиатурах Android и iOS, обозначая переключение языков. И тогда сразу будет понятно, что это за непонятный текст в шапке и как сделать понятно.

**Comment by tadatuta** [comment]
@palegrow спасибо!

**Comment by vithar** [comment]
Оставили только EN и RU.
