### ISSUE TITLE
Printing html-documents with code examples

### ISSUE THREAD

**Issue by godfreyd** [bem-site/bem.info#166]
![b575fcc9-06b0-4a94-a4a4-61cecbef9377](https://cloud.githubusercontent.com/assets/6197968/26090786/cf9d9cfa-3a0f-11e7-8f93-6dbcc28e9f07.JPG)
![27af056d-c663-4189-a53e-fc932540955f](https://cloud.githubusercontent.com/assets/6197968/26090787/cf9f4456-3a0f-11e7-98bc-e12796f8e93e.JPG)

**Comment by vithar** [comment]
Fixed in #177.
