### ISSUE TITLE
Incorrect link generation for the titles with quotes 

### ISSUE THREAD

**Issue by innabelaya** [bem-site/bem.info#170]
The link to the subtitle in the document does not work on the site due to the fact that the links on the site and on Github are not the same.
Link example from bem.info — https://ru.bem.info/methodology/faq/#Когда-создавать-булевый-модификатор-когда--модификатор-«ключ-значение»
Link from Github — https://github.com/bem-site/bem-method/blob/bem-info-data/faq/faq.ru.md#Когда-создавать-булевый-модификатор-когда--модификатор-ключ-значение

**Comment by vithar** [comment]
Fixed in #174
