### ISSUE TITLE
Блокировка в Украине

### ISSUE THREAD

**Issue by imkremen** [bem-site/bem.info#172]
В Украине ресурс заблокирован. Заблокирован по ошибке, так как его нет в санкционных списках.

**Comment by zxqfox** [comment]
Видимо, потому что где-то промелькнуло yandex в информации.

**Comment by vithar** [comment]
Всё должно работать, проверьте, пожалуйста, ещё раз.

**Comment by imkremen** [comment]
@vithar да, уже как пару месяцев назад доступ появился.
