### ISSUE TITLE
breadcrumbs ?

### ISSUE THREAD

**Issue by tormozz48** [bem-site/bem.info#18]
> breadcrumbs in gorshochek are awesome but not for this site, reverted

@vithar 

Да ты, батюшка, только скажи, как... а мы подхватим

![_355f44b78f4ce514a9f5d8f4fc856c29](https://cloud.githubusercontent.com/assets/996162/13186528/b0ac0e38-d757-11e5-947d-91dfa67d70be.png)

**Comment by vithar** [comment]
У тебя всё правильно сделано по части генерации хлебных крошек, так и должно быть.

Но у нас используются не полные хлебные крошки. Нет первой ссылки (у нас логотип вместо неё) и количество ссылок ограничивается глубиной поля site в модели.

Это очень кастомное поведение и если и нести его в горшочек, то каким-то отдельным модификатором для breadcrumbs, а не основным поведением.

**Comment by tormozz48** [comment]
> Это очень кастомное поведение и если и нести его в горшочек, то каким-то отдельным модификатором для breadcrumbs, а не основным поведением.

Смотри. Таски в горшочке - это независимые модули, часть которых можно реализовать внутри bem.info. Можно подумать в этом направлении.

Моя мысль такова, что нужно стремится генерировать данные в таком виде, чтобы их можно было максимально удобно шаблонизировать. Т.е. избавляться от каких-то сложных преобразований в шаблонах

**Comment by vithar** [comment]
Тогда надо взять всё из breadcrumbs.bemtree и куда-то сложить.
