### ISSUE TITLE
Fix list items 

### ISSUE THREAD

**Issue by godfreyd** [bem-site/bem.info#230]
<img width="1280" alt="2017-11-08 12 00 28" src="https://user-images.githubusercontent.com/6197968/32540091-a2c039c0-c47c-11e7-8cdd-e6fa5222a00a.png">

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem-site/bem.info/commit/2edf95f5249b1195ecaccd1c1fac51492b8c35ee
