### ISSUE TITLE
Сломаны картинки в меню и методологии

### ISSUE THREAD

**Issue by godfreyd** [bem-site/bem.info#248]
![2018-01-03 17_56_59-](https://user-images.githubusercontent.com/22275982/34523116-26cbd2a0-f0a7-11e7-8dfe-78ce85ca43c4.png)
![2018-01-03 17_51_45- _](https://user-images.githubusercontent.com/22275982/34523117-26f2a29a-f0a7-11e7-9b40-ff155ceaa605.png)

**Comment by a-lexxx** [comment]
Может что-то с кешем, потому что у меня вот прямо сейчас вроде бы отображается:
![image](https://user-images.githubusercontent.com/5994727/34716030-51b40228-f537-11e7-8868-c184704b7af0.png)

**Comment by tadatuta** [comment]
Can't reproduce
