### ISSUE TITLE
Fix code highlighting

### ISSUE THREAD

**Issue by tadatuta** [bem-site/bem.info#249]
Somewhere here https://github.com/bem-site/gorshochek/commit/93e5b21f59978376a9c7ecf53041c89dcdbd8c6b#diff-881f80dcf61488a64d956949bb5428c0R78 add `escapeContent: true`

**Comment by godfreyd** [comment]
Fix: https://github.com/bem-site/bem.info/commit/7115cac272f1df7002a28ffb05365194da346f0b
