### ISSUE TITLE
РКН заблокировал IP ru.bem.info на моём провайдере / In the fight with the windmills, Russian state Internet censorship agency blocked ru.bem.info IP

### ISSUE THREAD

**Issue by Zulcom** [bem-site/bem.info#299]
IP, полученный от DNS 1.1.1.1:  188.166.44.84 / IP providen by 1.1.1.1 DNS: 188.166.44.84
Город Красноярск / Krasnoyarsk City
Провайдер [Telecoma](http://rightside.ru/) искренне убеждает меня в том, что блокирует IP не он, а магистральный провайдер / MY ISP [Telecoma (ru site)](http://rightside.ru/) shift responsibility to   their backbone network provider
<center><h2>WinMTR statistics</h2></center>
<p align="center"> <table border="1" align="center">
<tr><td>Host</td> <td>%</td> <td>Sent</td> <td>Recv</td> <td>Best</td> <td>Avrg</td> <td>Wrst</td> <td>Last</td></tr>
<tr><td>192.168.0.1</td> <td>   0</td> <td>  25</td> <td>  25</td> <td>   0</td> <td>   0</td> <td>   1</td> <td>   0</td></tr>
<tr><td>193.173.144.217.rightside.ru</td> <td>   0</td> <td>  25</td> <td>  25</td> <td>   1</td> <td>   1</td> <td>   5</td> <td>   1</td></tr>
<tr><td>172.29.129.170</td> <td>   0</td> <td>  25</td> <td>  25</td> <td>   0</td> <td>   0</td> <td>   1</td> <td>   0</td></tr>
<tr><td>172.29.129.206</td> <td>   0</td> <td>  25</td> <td>  25</td> <td>   0</td> <td>   0</td> <td>   1</td> <td>   0</td></tr>
<tr><td>114.241.189.5.rightside.ru</td> <td>   0</td> <td>  25</td> <td>  25</td> <td>   0</td> <td>   6</td> <td> 141</td> <td>   1</td></tr>
<tr><td>37.29.81.137</td> <td>   0</td> <td>  25</td> <td>  25</td> <td>   0</td> <td>   1</td> <td>  20</td> <td>   1</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>   6</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
</table></body></html>
Как временное решение подключаюсь через IPv6, но его поддерживает лишь одно из моих устройств/ At now i'm use IPv6 to get access to site, but not all of my devices can use IPv6 protocol

**Comment by tadatuta** [comment]
@Zulcom есть такая беда, думаем, куда бы переехать, чтобы борцы с мельницами нас и на новом месте не достали...
