### ISSUE TITLE
Формат bem-config для сборки

### ISSUE THREAD

**Issue by tadatuta** [bem-site/bem.info#45]
Цитирую @blond.

В bem-config должно быть про какие есть уровни:

```
levels: {
    'lib/bem-core/common.blocks': { scheme: 'nested' },
    'lib/bem-core/desktop.blocks': { scheme: 'nested' },
    'common.blocks': { scheme: 'flat' },
    'desktop.blocks': { scheme: 'flat' }
}
```
- где-то ещё надо про то какие надо собирать нам, но это в самом gulp-конфиге.

// cc @zxqfox

**Comment by zxqfox** [comment]
А что мы-таки описывать будем уровни библиотек в главном конфиге? как-то не фонтан

**Comment by blond** [comment]
@zxqfox не, уровни библиотек должны быть в библиотеках. А в конфиге проекта должен быть список библиотек.

```js
libs: {
    'bem-core': './libs/bem-core',
    'bem-components': './libs/bem-components'
},
levels: {
    'common.blocks': { scheme: 'flat' },
    'desktop.blocks': { scheme: 'flat' }
}
```

При загрузке конфига поля levels должны мёржиться.

**Comment by zxqfox** [comment]
Кто должен мержить? bem-config?

**Comment by blond** [comment]
> Кто должен мержить? bem-config?

Кажется, да.

> Где/как будет описываться порядок для сборки?

В gulp-конфиге?

```
bem.src(['level1', 'level2'])
```

**Comment by zxqfox** [comment]
@blond как указать уровень внутри библиотеки? Библиотеки могут использовать другие библиотеки? Как подключать их уровни? Или это библиотека сама будет рулить? Если да, то как?

**Comment by zxqfox** [comment]
```
libs: {
    'components': './libs/bem-components' // core приедет из components?
},
```

**Comment by vithar** [comment]
@tadatuta это задача точно в правильном проекте?

**Comment by tadatuta** [comment]
Формулировку можно подправить, но здесь речь про то, что в bem.info нужно сложить конфиг, который будет говорить, как все это дело собрать на `gulp-bem`
