### ISSUE TITLE
Реализовать поддержку og:image

### ISSUE THREAD

**Issue by AnyaTyu** [bem-site/bem.info#70]
1) в bem-identity все логотипы сохранить как svg
2) сделать bem-identity библиотекой, подключаемой через bower
3) подключить эту библиотеку
4) добавить ротацию картинок в og:image из этой библиотеки, проверив перед этим, поддерживается svg в facebook

Пока сделал грязный хак для ускорения запуска:
https://github.com/vithar/bem.info/commit/d9634a4007e01fb75b9e00bc46dbc6566bedb16c

**Comment by tadatuta** [comment]
Хорошо бы и остальные мета-поля поддержать https://autonome.github.io/silobuster/

**Comment by vithar** [comment]
Сохранил картинки в `static/og_image` и настроил ротацию в nginx.
