### ISSUE TITLE
Обсудить: на /methodology/ после каждой фичи давать возможность перейти к документации

### ISSUE THREAD

**Issue by vithar** [bem-site/bem.info#72]
@veged предлагает на промо странице /methodology/ после каждой фичи добавить возможность перейти сразу в документацию, не долистывая страниницу до конца.

Т.е. если на середине страницы я понял, что уже «всё купил» — нужна возможность куда-то кликнуть и начать читать.

Варианты?

**Comment by AnyaTyu** [comment]
После promo-text в каждом блоке добавляем ссылочку "Читать далее" или "Перейти к документации"

**Comment by tadatuta** [comment]
мне лишние «читать далее» не очень нравятся. предлагаю:

1. добавить стандартные «уши» вперед-назад
2. превратить релевантные слова в тексте-подписи у каждого чанка в ссылку со всплывающим попапом-поясняшкой, что клик переведет в доку

**Comment by veged** [comment]
@tadatuta :+1:

**Comment by vithar** [comment]
Прикручу уши, покажу.

**Comment by vithar** [comment]
Ссылок со слов делать не надо, задача этой страницы увести на первый документ методологии, а не в разные разделы. А делать одну и ту же ссылку с разных слов как-то не очень.

**Comment by veged** [comment]
почему не очень, если все эти слова про одно и то же?

**Comment by vithar** [comment]
Инна, посмотри что тут можно сделать с точки зрения контента.

**Comment by innabelaya** [comment]
@vithar @tadatuta @veged посмотрите карту кликов на морде методологии — все кликают на картинки на стрелки, ожидая переход в документацию по каждому разделу. Плюс кликают на ключевые слова "масштабирование кода" или "единые правила".  Надо сделать кликабельными или картинки, или после описания фичи сделать стрелку-ссылку в доку. 
И в работе документ про основные принципы методологии. Кажется, можно уводить на него будет.
