### ISSUE TITLE
Firefox: extra empty space in methodology page promo-header

### ISSUE THREAD

**Issue by vithar** [bem-site/bem.info#92]
See https://yadi.sk/i/IGd9Xkr_rJY7j

**Comment by AnyaTyu** [comment]
Can't reproduce. Which version of FF ? https://yadi.sk/i/C7d7BCZArUgod

**Comment by vithar** [comment]
Fixed in 38964ed588c96b0e57b9c30a6fc2cce4f14fb3ff
